swagger: "2.0"
info:
  description: ""
  title: "Chat Service"
  version: "1.0.0"
schemes:
- "http"
paths:
  /chat/content:
    get:
      summary: "Find chat contents"
      produces:
      - "application/json"
      parameters:
      - name: "message"
        in: "query"
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
        500:
          description: "Internal error"
